"use babel";

export default [
  {
    name: ">Copy",
    category: "Core",
    command: "core:copy",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "c"],
  },
  {
    name: ">Copy Image",
    category: "Core",
    command: "core:copy-image",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Copy Note Link",
    category: "Core",
    command: "core:copy-note-link",
    selector: ".note-list-bar",
    shortcut: ["ctrl", "c"],
  },
  {
    name: ">Cut",
    category: "Core",
    command: "core:cut",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "x"],
  },
  {
    name: ">Delete Note",
    category: "Core",
    command: "core:delete-note",
    selector: ".note-list-bar",
    shortcut: ["ctrl", "bkspc"],
  },
  {
    name: ">Delete Notebook",
    category: "Core",
    command: "core:delete-notebook",
    state: "disabled",
    shortcut: [""],
  },
  {
    name: ">Delete Tag",
    category: "Core",
    command: "core:delete-tag",
    state: "disabled",
    shortcut: [""],
  },
  {
    name: ">Duplicate Note",
    category: "Core",
    command: "core:duplicate-note",
    selector: ".note-list-bar",
    shortcut: ["ctrl", "d"],
  },
  {
    name: ">Empty Trash",
    category: "Core",
    command: "core:empty-trash",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Filter notes",
    category: "Core",
    command: "core:filter-notes",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Filter by tag",
    category: "Core",
    command: "core:filter-by-tag",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Find",
    category: "Core",
    command: "core:find",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "shft", "f"],
  },
  {
    name: ">Clear search bar",
    category: "Core",
    command: "core:find-clear",
    selector: ".note-list-search-bar input",
    shortcut: ["esc"],
  },
  {
    name: ">Find (Global)",
    category: "Core",
    command: "core:find-global",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "alt", "shft", "f"],
  },
  {
    name: ">Focus next",
    category: "Core",
    command: "core:focus-next",
    selector: "body",
    state: "notworking",
    shortcut: ["tab"],
  },
  {
    name: ">Focus note list bar",
    category: "Core",
    command: "core:focus-note-list-bar",
    selector: ".note-list-search-bar input",
    state: "notworking",
    shortcut: ["ctrl", "alt", "l"],
  },
  {
    name: ">Focus previous",
    category: "Core",
    command: "core:focus-previous",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Move notebook",
    category: "Core",
    command: "core:move-notebook",
    state: "disabled",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Move to notebook",
    category: "Core",
    command: "core:move-to-notebook",
    selector: ".note-list-bar",
    shortcut: ["ctrl", "alt", "m"],
  },
  {
    name: ">Navigate back",
    category: "Core",
    command: "core:navigate-back",
    selector: "body",
    shortcut: ["alt", "left"],
  },
  {
    name: ">Navigate forward",
    category: "Core",
    command: "core:navigate-forward",
    selector: "body",
    shortcut: ["alt", "right"],
  },
  {
    name: ">New Note",
    category: "Core",
    command: "core:new-note",
    selector: "body",
    shortcut: ["ctrl", "n"],
  },
  {
    name: ">New Notebook",
    category: "Core",
    command: "core:new-notebook",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Show all notes",
    category: "Core",
    command: "core:note-list-show-all-notes",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Show all notes in specified notebook",
    category: "Core",
    command: "core:note-list-show-notes-in-book",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Show all notes by tag",
    category: "Core",
    command: "core:notes-list-show-notes-with-tag",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Show all notes with status",
    category: "Core",
    command: "core:note-list-show-notes-with-status",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Show notes in book of editing note",
    category: "Core",
    command: "core:note-list-show-notes-in-book-of-editing-note",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Open first note",
    category: "Core",
    command: "core:open-first-note",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Open next note",
    category: "Core",
    command: "core:open-next-note",
    selector: "body",
    shortcut: ["ctrl", "tab"],
  },
  {
    name: ">Close note",
    category: "Core",
    command: "core:close-note",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Open note",
    category: "Core",
    command: "core:open-note",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Open note in separate window",
    category: "Core",
    command: "core:open-note-in-separate-window",
    selector: "body",
    shortcut: ["shft", "return"],
  },
  {
    name: ">Open previous note",
    category: "Core",
    command: "core:open-prev-note",
    selector: "body",
    shortcut: ["ctrl", "shift", "tab"],
  },
  {
    name: ">Open tag settings",
    category: "Core",
    command: "core:open-tag-settings",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Paste",
    category: "Core",
    command: "core:paste",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "v"],
  },
  {
    name: ">Redo",
    category: "Core",
    command: "core:redo",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "y"],
  },
  {
    name: ">Rename Notebook",
    category: "Core",
    command: "core:rename-notebook",
    selector: "body",
    state: "disabled",
    shortcut: [""],
  },
  {
    name: ">Save Image",
    category: "Core",
    command: "core:save-image",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Save Note",
    category: "Core",
    command: "core:save-note",
    selector: "body",
    shortcut: ["ctrl", "s"],
  },
  {
    name: ">Select all",
    category: "Core",
    command: "core:select-all",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "a"],
  },
  {
    name: ">Search notes",
    category: "Core",
    command: "core:search-notes",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Share note",
    category: "Core",
    command: "core:share-note",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Show note revisions",
    category: "Core",
    command: "core:show-note-revisions",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ">Focus sidebar",
    category: "Core",
    command: "core:sidebar-focus",
    selector: "body",
    state: "notworking",
    shortcut: ["shft", "tab"],
  },
  {
    name: ">Select next item on sidebar",
    category: "Core",
    command: "core:sidebar-select-next-item",
    selector: "body",
    shortcut: ["up"],
  },
  {
    name: ">Select previous item on sidebar",
    category: "Core",
    command: "core:sidebar-select-prev-item",
    selector: "body",
    shortcut: ["down"],
  },
  {
    name: ">Disclose item on sidebar",
    category: "Core",
    command: "core:sidebar-disclose-item",
    selector: "body",
    shortcut: ["enter"],
  },
  {
    name: ">Expand item on sidebar",
    category: "Core",
    command: "core:sidebar-expand-item",
    selector: "body",
    shortcut: ["right"],
  },
  {
    name: ">Collapse item on sidebar",
    category: "Core",
    command: "core:sidebar-collapse-item",
    selector: "body",
    shortcut: ["left"],
  },
  {
    name: ">Undo",
    category: "Core",
    command: "core:undo",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "z"],
  },
  {
    name: ">Toggle editor drawer",
    category: "Core",
    command: "core:toggle-editor-drawer",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "j"],
  },
  {
    name: ">Show editor drawer",
    category: "Core",
    command: "core:show-editor-drawer",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ">Close editor drawer",
    category: "Core",
    command: "core:close-editor-drawer",
    selector: "body",
    shortcut: ["esc"],
  },
  {
    name: ">Do nothing",
    category: "Core",
    command: "core:do-nothing",
    selector: ".editor-header-title-input input",
    state: "notworking",
    shortcut: ["ctrl", "w"],
  },
  {
    name: ">Copy preview selection",
    category: "Core",
    command: "core:do-nothing",
    selector: ".mde-preview",
    state: "notworking",
    shortcut: ["ctrl", "c"],
  },
  {
    name: ">Hide workspace menu on sidebar",
    category: "Core",
    command: "core:sidebar-hide-workspace-menu",
    selector: ".sidebar-workspace-menu",
    state: "notworking",
    shortcut: ["bkspc"],
  },
  {
    name: ">Unpin/Pin note to top",
    category: "Core",
    command: "core:pin-note-to-top",
    selector: ".note-list-bar",
    shortcut: ["p"],
  },
  {
    name: ">Submit",
    category: "Core",
    command: "core:submit",
    selector: ".input-datetime",
    state: "notworking",
    shortcut: ["return"],
  },
  {
    name: ">Cancel",
    category: "Core",
    command: "core:cancel",
    selector: ".input-datetime",
    state: "notworking",
    shortcut: ["esc"],
  },
  {
    name: ">Move up on list bar",
    category: "Core",
    command: "core:list-bar-move-up",
    selector: ".list-bar",
    state: "notworking",
    shortcut: ["up"],
  },
  {
    name: ">Move down on list bar",
    category: "Core",
    command: "core:list-bar-move-down",
    selector: ".list-bar",
    state: "notworking",
    shortcut: ["down"],
  },
  {
    name: ">Invoke submit on list bar",
    category: "Core",
    command: "core:list-bar-submit",
    selector: ".list-bar",
    state: "notworking",
    shortcut: ["return"],
  },
  {
    name: ">Cancel list bar action",
    category: "Core",
    command: "core:list-bar-cancel",
    selector: ".list-bar",
    state: "notworking",
    shortcut: ["esc"],
  },
  {
    name: ">Move up on notebook list",
    category: "Core",
    command: "core:notebook-list-bar-input-move-up",
    selector: ".notebook-list-bar input",
    state: "notworking",
    shortcut: ["up"],
  },
  {
    name: ">Move down on notebook list",
    category: "Core",
    command: "core:notebook-list-bar-input-move-down",
    selector: ".notebook-list-bar input",
    state: "notworking",
    shortcut: ["down"],
  },
  {
    name: ">Invoke submit on notebook list",
    category: "Core",
    command: "core:notebook-list-bar-input-move-submit",
    selector: ".notebook-list-bar input",
    state: "notworking",
    shortcut: ["return"],
  },
];
