"use babel";
export default [
{
name: ".Clear find",
category: "Editor",
command: "editor:clear-find",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Change note status none",
category: "Editor",
command: "editor:change-note-status-none",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Change note status active",
category: "Editor",
command: "editor:change-note-status-active",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Change note status onhold",
category: "Editor",
command: "editor:change-note-status-onhold",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Change note status completed",
category: "Editor",
command: "editor:change-note-status-completed",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Change note status dropped",
category: "Editor",
command: "editor:change-note-status-dropped",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete char after",
category: "Editor",
command: "editor:delete-char-after",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete char before",
category: "Editor",
command: "editor:delete-char-before",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete group after",
category: "Editor",
command: "editor:delete-group-after",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete group before",
category: "Editor",
command: "editor:delete-group-before",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete line",
category: "Editor",
command: "editor:delete-line",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete word after",
category: "Editor",
command: "editor:delete-word-after",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete word before",
category: "Editor",
command: "editor:delete-word-before",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete wrapped line left",
category: "Editor",
command: "editor:delete-wrapped-line-left",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Delete wrapped line right",
category: "Editor",
command: "editor:delete-wrapped-line-right",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Find",
category: "Editor",
command: "editor:find",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Find next",
category: "Editor",
command: "editor:find-next",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Find prev",
category: "Editor",
command: "editor:find-prev",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Find text",
category: "Editor",
command: "editor:find-text",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Focus",
category: "Editor",
command: "editor:focus",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Focus mde",
category: "Editor",
command: "editor:focus-mde",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Focus preview",
category: "Editor",
command: "editor:focus-preview",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go char left",
category: "Editor",
command: "editor:go-char-left",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go char right",
category: "Editor",
command: "editor:go-char-right",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go doc end",
category: "Editor",
command: "editor:go-doc-end",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go doc start",
category: "Editor",
command: "editor:go-doc-start",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go group left",
category: "Editor",
command: "editor:go-group-left",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go group right",
category: "Editor",
command: "editor:go-group-right",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go line down",
category: "Editor",
command: "editor:go-line-down",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go line end",
category: "Editor",
command: "editor:go-line-end",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go line left",
category: "Editor",
command: "editor:go-line-left",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go line right",
category: "Editor",
command: "editor:go-line-right",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go line start",
category: "Editor",
command: "editor:go-line-start",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go line up",
category: "Editor",
command: "editor:go-line-up",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go page down",
category: "Editor",
command: "editor:go-page-down",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go page up",
category: "Editor",
command: "editor:go-page-up",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go word left",
category: "Editor",
command: "editor:go-word-left",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Go word right",
category: "Editor",
command: "editor:go-word-right",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Indent",
category: "Editor",
command: "editor:indent",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Indent less",
category: "Editor",
command: "editor:indent-less",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Indent more",
category: "Editor",
command: "editor:indent-more",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Insert images",
category: "Editor",
command: "editor:insert-images",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Jump to line",
category: "Editor",
command: "editor:jump-to-line",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Kill line",
category: "Editor",
command: "editor:kill-line",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".New line",
category: "Editor",
command: "editor:new-line",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Open line",
category: "Editor",
command: "editor:open-line",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Redo selection",
category: "Editor",
command: "editor:redo-selection",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Replace",
category: "Editor",
command: "editor:replace",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Replace selection",
category: "Editor",
command: "editor:replace-selection",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Save editor scroll",
category: "Editor",
command: "editor:save-editor-scroll",
selector: "It's a private command",
state: "inprogress",
shortcut: [""],
},
{
name: ".Save preview scroll",
category: "Editor",
command: "editor:save-preview-scroll",
selector: "It's a private command",
state: "inprogress",
shortcut: [""],
},
{
name: ".Scroll editor to line",
category: "Editor",
command: "editor:scroll-editor-to-line",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Scroll preview to line",
category: "Editor",
command: "editor:scroll-preview-to-line",
selector: "body",
state: "inprogress",
shortcut: [""],
},
{
name: ".Select all",
category: "Editor",
command: "editor:select-all",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Select lines downward",
category: "Editor",
command: "editor:select-lines-downward",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Select lines upward",
category: "Editor",
command: "editor:select-lines-upward",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Single selection",
category: "Editor",
command: "editor:single-selection",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Toggle overwrite",
category: "Editor",
command: "editor:toggle-overwrite",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Toggle task list",
category: "Editor",
command: "editor:toggle-task-list",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Transpose chars",
category: "Editor",
command: "editor:transpose-chars",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Undo selection",
category: "Editor",
command: "editor:undo-selection",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
{
name: ".Unindent",
category: "Editor",
command: "editor:unindent",
selector: ".mde-cm-wrapper",
state: "inprogress",
shortcut: [""],
},
];