"use babel";
export default [
  {
    name: ".Clear find",
    category: "Editor",
    command: "editor:clear-find",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ".Change note status to none",
    category: "Editor",
    command: "editor:change-note-status-none",
    selector: "body",
    shortcut: ["alt", "shft", "1"],
  },
  {
    name: ".Change note status to active",
    category: "Editor",
    command: "editor:change-note-status-active",
    selector: "body",
    shortcut: ["alt", "shft", "2"],
  },
  {
    name: ".Change note status to onhold",
    category: "Editor",
    command: "editor:change-note-status-onhold",
    selector: "body",
    shortcut: ["alt", "shft", "3"],
  },
  {
    name: ".Change note status to completed",
    category: "Editor",
    command: "editor:change-note-status-completed",
    selector: "body",
    shortcut: ["alt", "shft", "4"],
  },
  {
    name: ".Change note status to dropped",
    category: "Editor",
    command: "editor:change-note-status-dropped",
    selector: "body",
    shortcut: ["alt", "shft", "5"],
  },
  {
    name: ".Delete char after",
    category: "Editor",
    command: "editor:delete-char-after",
    selector: ".mde-cm-wrapper",
    shortcut: ["delete"],
  },
  {
    name: ".Delete char before",
    category: "Editor",
    command: "editor:delete-char-before",
    selector: ".mde-cm-wrapper",
    shortcut: ["bkspc"],
  },
  {
    name: ".Delete group after",
    category: "Editor",
    command: "editor:delete-group-after",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "delete"],
  },
  {
    name: ".Delete group before",
    category: "Editor",
    command: "editor:delete-group-before",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "bkspc"],
  },
  {
    name: ".Delete line",
    category: "Editor",
    command: "editor:delete-line",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "d"],
  },
  {
    name: ".Delete word after",
    category: "Editor",
    command: "editor:delete-word-after",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Delete word before",
    category: "Editor",
    command: "editor:delete-word-before",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Delete wrapped line left",
    category: "Editor",
    command: "editor:delete-wrapped-line-left",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Delete wrapped line right",
    category: "Editor",
    command: "editor:delete-wrapped-line-right",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Find",
    category: "Editor",
    command: "editor:find",
    selector: "body",
    shortcut: ["ctrl", "f"],
  },
  {
    name: ".Find next",
    category: "Editor",
    command: "editor:find-next",
    selector: "body",
    shortcut: ["ctrl", "g"],
  },
  {
    name: ".Find prev",
    category: "Editor",
    command: "editor:find-prev",
    selector: "body",
    shortcut: ["ctrl", "shft", "g"],
  },
  {
    name: ".Find text",
    category: "Editor",
    command: "editor:find-text",
    selector: "body",
    shortcut: [""],
  },
  {
    name: ".Focus",
    category: "Editor",
    command: "editor:focus",
    selector: "body",
    state: "notworking",
    shortcut: ["ctrl", "return"],
  },
  {
    name: ".Focus Markdown Editor",
    category: "Editor",
    command: "editor:focus-mde",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Focus preview",
    category: "Editor",
    command: "editor:focus-preview",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Go to left of character",
    category: "Editor",
    command: "editor:go-char-left",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["left"],
  },
  {
    name: ".Go to right of character",
    category: "Editor",
    command: "editor:go-char-right",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["right"],
  },
  {
    name: ".Go to document end",
    category: "Editor",
    command: "editor:go-doc-end",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "end"],
  },
  {
    name: ".Go to document start",
    category: "Editor",
    command: "editor:go-doc-start",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "home"],
  },
  {
    name: ".Go group left",
    category: "Editor",
    command: "editor:go-group-left",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["ctrl", "left"],
  },
  {
    name: ".Go group right",
    category: "Editor",
    command: "editor:go-group-right",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["ctrl", "right"],
  },
  {
    name: ".Go line down",
    category: "Editor",
    command: "editor:go-line-down",
    selector: ".mde-cm-wrapper",
    shortcut: ["down"],
  },
  {
    name: ".Go line end",
    category: "Editor",
    command: "editor:go-line-end",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["end"],
  },
  {
    name: ".Go line left",
    category: "Editor",
    command: "editor:go-line-left",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Go line right",
    category: "Editor",
    command: "editor:go-line-right",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Go line start",
    category: "Editor",
    command: "editor:go-line-start",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["home"],
  },
  {
    name: ".Go line up",
    category: "Editor",
    command: "editor:go-line-up",
    selector: ".mde-cm-wrapper",
    shortcut: ["up"],
  },
  {
    name: ".Go page down",
    category: "Editor",
    command: "editor:go-page-down",
    selector: ".mde-cm-wrapper",
    shortcut: ["page down"],
  },
  {
    name: ".Go page up",
    category: "Editor",
    command: "editor:go-page-up",
    selector: ".mde-cm-wrapper",
    shortcut: ["page up"],
  },
  {
    name: ".Go word left",
    category: "Editor",
    command: "editor:go-word-left",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Go word right",
    category: "Editor",
    command: "editor:go-word-right",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Indent",
    category: "Editor",
    command: "editor:indent",
    selector: ".mde-cm-wrapper",
    shortcut: ["tab"],
  },
  {
    name: ".Indent less",
    category: "Editor",
    command: "editor:indent-less",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "["],
  },
  {
    name: ".Indent more",
    category: "Editor",
    command: "editor:indent-more",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "]"],
  },
  {
    name: ".Insert images",
    category: "Editor",
    command: "editor:insert-images",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Jump to line",
    category: "Editor",
    command: "editor:jump-to-line",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["ctrl", "g"],
  },
  {
    name: ".Delete line",
    category: "Editor",
    command: "editor:kill-line",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".New line",
    category: "Editor",
    command: "editor:new-line",
    selector: ".mde-cm-wrapper",
    shortcut: ["return"],
  },
  {
    name: ".Open line",
    category: "Editor",
    command: "editor:open-line",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Open link",
    category: "Editor",
    command: "editor:open-link",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "alt", "o"],
  },
  {
    name: ".Redo selection",
    category: "Editor",
    command: "editor:redo-selection",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shft", "u"],
  },
  {
    name: ".Replace",
    category: "Editor",
    command: "editor:replace",
    selector: "body",
    shortcut: ["ctrl", "alt", "f"],
  },
  {
    name: ".Replace selection",
    category: "Editor",
    command: "editor:replace-selection",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Save editor scroll",
    category: "Editor",
    command: "editor:save-editor-scroll",
    selector: "core:unknown",
    state: "disabled",
    shortcut: [""],
  },
  {
    name: ".Save preview scroll",
    category: "Editor",
    command: "editor:save-preview-scroll",
    selector: "core:unknown",
    state: "disabled",
    shortcut: [""],
  },
  {
    name: ".Scroll editor to line",
    category: "Editor",
    command: "editor:scroll-editor-to-line",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Scroll preview to line",
    category: "Editor",
    command: "editor:scroll-preview-to-line",
    selector: "body",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Select all",
    category: "Editor",
    command: "editor:select-all",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "a"],
  },
  {
    name: ".Select lines downward",
    category: "Editor",
    command: "editor:select-lines-downward",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shift", "down"],
  },
  {
    name: ".Select lines upward",
    category: "Editor",
    command: "editor:select-lines-upward",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shift", "up"],
  },
  {
    name: ".Single selection",
    category: "Editor",
    command: "editor:single-selection",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["esc"],
  },
  {
    name: ".Toggle overwrite",
    category: "Editor",
    command: "editor:toggle-overwrite",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: ["insert"],
  },
  {
    name: ".Toggle task list",
    category: "Editor",
    command: "editor:toggle-task-list",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Transpose chars",
    category: "Editor",
    command: "editor:transpose-chars",
    selector: ".mde-cm-wrapper",
    state: "notworking",
    shortcut: [""],
  },
  {
    name: ".Undo selection",
    category: "Editor",
    command: "editor:undo-selection",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "alt", "u"],
  },
  {
    name: ".Unindent",
    category: "Editor",
    command: "editor:unindent",
    selector: ".mde-cm-wrapper",
    shortcut: ["shft", "tab"],
  },
  {
    name: ".Move focus to next",
    category: "Editor",
    command: "editor:move-focus-to-next",
    selector: ".editor-header-title-input input",
    state: "buggy",
    shortcut: ["return"],
  },
  {
    name: ".Focus title",
    category: "Editor",
    command: "editor:title:focus",
    selector: ".note-list-bar",
    state: "notworking",
    shortcut: ["return"],
  },
];
