"use babel";

export default [
  {
    name: ".Emphasize Text",
    category: "Format",
    command: "core:emphasize",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "i"],
  },
  {
    name: ".Indent",
    category: "Format",
    command: "core:indent",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Insert code block",
    category: "Format",
    command: "core:insert-code-block",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shft", "c"],
  },
  {
    name: ".Insert horizontal rule",
    category: "Format",
    command: "core:insert-horizontal-rule",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shft", "h"],
  },
  {
    name: ".Insert link",
    category: "Format",
    command: "core:insert-link",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "k"],
  },
  {
    name: ".Indent",
    category: "Format",
    command: "core:indent",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Insert code block",
    category: "Format",
    command: "core:insert-code-block",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Strikethrough",
    category: "Format",
    command: "core:strikethrough",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "u"],
  },
  {
    name: ".Embolden",
    category: "Format",
    command: "core:strong",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "b"],
  },
  {
    name: ".Toggle blockquote",
    category: "Format",
    command: "core:toggle-blockquote",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "'"],
  },
  {
    name: ".Toggle bulleted list",
    category: "Format",
    command: "core:toggle-bulleted-list",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shft", "l"],
  },
  {
    name: ".Toggle heading 1",
    category: "Format",
    command: "core:toggle-heading-1",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "1"],
  },
  {
    name: ".Toggle heading 2",
    category: "Format",
    command: "core:toggle-heading-2",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "2"],
  },
  {
    name: ".Toggle heading 3",
    category: "Format",
    command: "core:toggle-heading-3",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "3"],
  },
  {
    name: ".Toggle heading 4",
    category: "Format",
    command: "core:toggle-heading-4",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "4"],
  },
  {
    name: ".Make header bigger",
    category: "Format",
    command: "core:toggle-heading-bigger",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Make header smaller",
    category: "Format",
    command: "core:toggle-heading-smaller",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
  {
    name: ".Toggle numbered list",
    category: "Format",
    command: "core:toggle-numbered-list",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shft", "o"],
  },
  {
    name: ".Toggle task list",
    category: "Format",
    command: "core:toggle-task-list",
    selector: ".mde-cm-wrapper",
    shortcut: ["ctrl", "shft", "t"],
  },
  {
    name: ".Unindent",
    category: "Format",
    command: "core:unindent",
    selector: ".mde-cm-wrapper",
    shortcut: [""],
  },
];
