"use babel";
export default [
  {
    name: ">Sort by date created",
    category: "View",
    command: "view:sort-by-date-created",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Sort by date updated",
    category: "View",
    command: "view:sort-by-date-updated",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Sort by title",
    category: "View",
    command: "view:sort-by-title",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Sort in ascending",
    category: "View",
    command: "view:sort-in-ascending",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Sort in descending",
    category: "View",
    command: "view:sort-in-descending",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Toggle distraction free",
    category: "View",
    command: "view:toggle-distraction-free",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Toggle preview",
    category: "View",
    command: "view:toggle-preview",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Toggle side by side",
    category: "View",
    command: "view:toggle-side-by-side",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Toggle sidebar",
    category: "View",
    command: "view:toggle-sidebar",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
];
