"use babel";
export default [
  {
    name: ">Close",
    category: "Window",
    command: "window:close",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Decrease font size",
    category: "Window",
    command: "window:decrease-font-size",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Increase font size",
    category: "Window",
    command: "window:increase-font-size",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Install shell commands",
    category: "Window",
    command: "window:install-shell-commands",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">New inkdrop window",
    category: "Window",
    command: "window:new-inkdrop-window",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Reload",
    category: "Window",
    command: "window:reload",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Toggle dev tools",
    category: "Window",
    command: "window:toggle-dev-tools",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
  {
    name: ">Toggle full screen",
    category: "Window",
    command: "window:toggle-full-screen",
    selector: "body",
    state: "inprogress",
    shortcut: [""],
  },
];
